dict = {
    "efficient [ɪˈfɪʃnt]": "эффективный",
    "revision [rɪˈvɪʒən]": "ревизия",
    "provide [prəˈvaɪd]": "обеспечивать",
    "revise [rɪˈvaɪz]": "пересматривать",
    "divide [dɪˈvaɪd]": "делить",
    "clockwise [ˈklɒkwaɪz]": "по часовой стрелке",
    "elicit [ɪˈlɪsɪt]": "вызывать, выявлять",
    "respond [rɪsˈpɒnd]": "откликнуться",
    "suggest [səˈʤest]": "предлагать",
    "particular [pəˈtɪkjʊlə]": "определенный",
    "fit [fɪt]": "подходить",
    "remind [ˈrɪmaɪnd]": "напоминать",
    "common [ˈkɒmən]": "общий",
    "whether [ˈweðə]": "будь то",
    "follow up [ˈfɒləʊ ʌp]": "следить, отслеживать",
    "encourage [ɪnˈkʌrɪʤ]": "поощрять",
    "auxiliary [ɔːgˈzɪljərɪ]": "вспомогательный",
    "beverage [ˈbevərɪʤ]": "напиток",
    "partition [pɑːˈtɪʃn]": "раздел, секция",
    "following [ˈfɒləʊɪŋ]": "следующий, нижеследующий",
    "write down [raɪt daʊn]": "записывать",
    "cross out [krɒs aʊt]": "вычеркнуть",
    "tick [tɪk]": "галочка",
    "cross [krɒs]": "пересекать",
    "drill [drɪl]": "упражнение",
    "match [mæʧ]": "совпадение",
    "syllable [ˈsɪləbl]": "слог",
    "point out [pɔɪnt aʊt]": "отмечать",
    "chart [ʧɑːt]": "диаграмма",
    "jogging [ˈʤɒgɪŋ]": "пробежка",
    "psychiatrist [saɪˈkaɪətrɪst]": "психиатр",
    "turn on [tɜːn ɒn]": "включить",
    "rub [rʌb]": "тереть",
    "fair [feə]": "справедливый, красивый, светлый",
    "talkative [ˈtɔːkətɪv]": "разговорчивый",
    "generous [ˈʤenərəs]": "щедрый",
    "funny [ˈfʌnɪ]": "забавный",
    "shy [ʃaɪ]": "застенчивый",
    "neck [nek]": "шея",
    "ink [ɪŋk]": "чернила",
    "bite [baɪt]": "кусать",
    "guess [ges]": "догадываться",
    "expression [ɪksˈpreʃn]": "выражение",
    "cooker [ˈkʊkə]": "кухонная плита",
    "mean [miːn]": "подлый",
    "quiet [ˈkwaɪət]": "спокойный",
    "definition [defɪˈnɪʃn]": "определение",
    "get on [get ɔn]": "ладить",
    "suspense [səsˈpens]": "неизвестность",
    "sheet [ʃiːt]": "лист",
    "further [ˈfɜːðə]": "дальнейший",
    "next to [nekst tuː]": "рядом с",
    "sketch [skeʧ]": "набросок, зарисовка",
    "chin [ʧɪn]": "подбородок",
    "below [bɪˈləʊ]": "ниже",
    "liver [ˈlɪvə]": "печень",
    "attendant [əˈtendənt]": "сопровождающий",
    "at least [æt liːst]": "по крайней мере",
    "get up [get ʌp]": "вставать, просыпаться",
    "tidy [ˈtaɪdɪ]": "аккуратный, убирать",
    "hospitable [ˈhɔspɪtəbl]": "гостеприимный",
    "defining [dɪˈfaɪnɪŋ]": "определяющий",
    "amuse [əˈmjuːz]": "развлекать",
    "cynical [ˈsɪnɪkəl]": "циничный",
    "clause [klɔːz]": "пункт, статья, раздел",
    "paraphrase [ˈpærəfreɪz]": "перефразировать, пересказ",
    "remain [rɪˈmeɪn]": "находиться",
    "stamp [stæmp]": "марки, печать",
    "instead [ɪn'sted]": "вместо",
    "omission [əˈmɪʃn]": "упущение",
    "department store [dɪˈpɑːtmənt stɔː]": "универмаг",
    "measure [ˈmeʒə]": "мера",
    "slightly [ˈslaɪtlɪ]": "слегка",
    "purpose [ˈpɜːpəs]": "цель",
    "pleased [pliːzd]": "довольный",
    "properly [ˈprɒpəlɪ]": "должным образом",
    "divorced [dɪˈvɔːst]": "разведенный",
    "up to [ˈʌp tuː]": "вплоть до",
    "summary [ˈsʌmərɪ]": "резюме, сводка",
    "feature [ˈfiːʧə]": "особенность",
    "however [haʊˈevə]": "однако",
    "probably [ˈprɒbəblɪ]": "возможно",
    "disaster [dɪˈzɑːstə]": "катастрофа",
    "pretend [prɪˈtend]": "притворяться",
    "terrible [ˈterəbl]": "ужасный",
    "expand [ɪksˈpænd]": "расширять",
    "extend [ɪksˈtend]": "расширять",
    "precise [prɪˈsaɪs]": "точный",
    "pedestrian [pɪˈdestrɪən]": "пешеход",
    "sightseeing [ˈsaɪtsiːɪŋ]": "осмотр достопримечательностей",
    "sunbathe [ˈsʌnbeɪð]": "загорать",
    "camping [ˈkæmpɪŋ]": "поход, палатка",
    "hire [ˈhaɪə]": "нанимать, арендовать",
    "windy [ˈwɪndɪ]": "ветренный",
    "foggy [ˈfɒgɪ]": "туманный",
    "boiling [ˈbɔɪlɪŋ]": "кипячение",
    "miserable [ˈmɪz(ə)rəb(ə)l]": "несчастный",
    "furious [ˈfjʊərɪəs]": "яростный",
    "heat [hiːt]": "жара",
    "heatwave [ˈhiːtweɪv]": "период сильной жары",
    "vast [vɑːst]": "обширный",
    "majority [məˈʤɒrɪtɪ]": "большинство, большая часть",
    "reference [ˈrefrəns]": "ссылка, источник, справочник",
    "shout [ʃaʊt]": "крик",
    "comprehension [kɒmprɪˈhenʃn]": "понимание",
    "capture [ˈkæpʧə]": "захватить, отразить",
    "behind [bɪˈhaɪnd]": "позади, сзади",
    "ridiculous [rɪˈdɪkjʊləs]": "нелепый",
    "confident [ˈkɒnfɪdənt]": "уверенный",
    "stolen [ˈstəʊlən]": "украденный",
    "punish [ˈpʌnɪʃ]": "наказывать",
    "annoying [əˈnɔɪɪŋ]": "раздражающий",
    "blame [bleɪm]": "вина",
    "scary [ˈske(ə)rɪ]": "страшный, жуткий",
    "merge [mɜːʤ]": "поглощать",
    "remote [rɪˈməʊt]": "удаленный",
    "comparison [kəmˈpærɪsn]": "сравнение",
    "resign [riːˈsaɪn]": "уходить в отставку",
    "prevent [prɪˈvent]": "предотвращать",
    "luckily [ˈlʌkɪlɪ]": "к счастью",
    "eternal [ɪˈtɜːn(ə)l]": "вечный",
    "occur [əˈkɜː]": "происходить",
    "refer [rɪˈfɜː]": "относиться",
    "possibility [pɒsəˈbɪlɪtɪ]": "возможность",
    "inspiration [ɪnspɪˈreɪʃn]": "вдохновение",
    "terribly [ˈterəblɪ]": "ужасно",
    "admit [ədˈmɪt]": "признавать",
    "deserve [dɪˈzɜːv]": "заслуживать",
    "possessions [pəˈzeʃnz]": "пожитки",
    "possession [pəˈzeʃn]": "владение",
    "belong [bɪˈlɒŋ]": "принадлежать",
    "wonder [ˈwʌndə]": "удивляться, спрашивть",
    "invent [ɪnˈvent]": "изобретать",
    "madly [ˈmædlɪ]": "безумно",
    "along [əˈlɒŋ]": "вдоль",
    "recycle [riːˈsaɪkl]": "повторно использовать, перерабатывать",
    "deciphering [dɪˈsaɪfərɪŋ]": "расшифровка",
    "aid [eɪd]": "помощь, поддержка",
    "envelope [ˈenvələʊp]": "конверт",
    "wheat [wiːt]": "пшеница",
    "beep [biːp]": "гудок",
    "attach [əˈtæʧ]": "прикреплять",
    "horrible [ˈhɒrəbl]": "ужасный",
    "pouring [ˈpɔːrɪŋ]": "проливной",
    "pity [ˈpɪtɪ]": "жалость",
    "go out [gəʊ aʊt]": "выходить",
    "pick up [pɪk ʌp]": "подбирать",
    "change [ʧeɪnʤ]": "сдача",
    "receipt [rɪˈsiːt]": "чек",
    "escape [ɪsˈkeɪp]": "побег",
    "break up [breɪk ʌp]": "расставаться",
    "notice [ˈnəʊtɪs]": "уведомление, внимание",
    "pass by": "проходить мимо",
    "shelf [ʃelf]": "полка",
    "Easter [ˈiːstə]": "пасха",
    "memorable [ˈmem(ə)rəb(ə)l]": "памятный",
    "involve [ɪnˈvɒlv]": "вовлекать",
    "sympathetic [sɪmpəˈθetɪk]": "сочуственный",
    "nasty [ˈnɑːstɪ]": "противный",
    "approve [əˈpruːv]": "одобрить",
    "Bureau [ˈbjʊ(ə)rəʊ]": "бюро, контора",
    "consolidate [kənˈsɒlɪdɪt]": "объединять",
    "arrangements [əˈreɪnʤmənts]": "договоренности",
    "establish [ɪsˈtæblɪʃ]": "установить",
    "omit [əˈmɪt]": "пропускать",
    "afford": "позволить себе",
    "look forward to [lʊk ˈfɔːwəd tuː]": "ждать с нетерпением",
    "borrow [ˈbɒrəʊ]": "одолжить, занятьб брать взаймы",
    "lend [lend]": "одалживть",
    "cheer up [ʧɪə ʌp]": "подбадривать, развеселить",
    "appropriate [ə'prəuprɪət]": "подходящий",
    "perhaps [pəˈhæps]": "возможно",
    "point out [pɔɪnt aʊt]": "показывать, указывать",
    "probably [ˈprɒbəblɪ]": "возможно",
    "cold [kəʊld]": "простуда",
    "certain [sɜːtn]": "определенный",
    "plumber [ˈplʌmə]": "сантехник",
    "involving [ɪnˈvɒlvɪŋ]": "включающий",
    "either [ˈaɪðə]": "оба",
    "needle [niːdl]": "игла",
    "effort [ˈefət]": "усилие",
    "exist [ɪgˈzɪst]": "существовать",
    "concern [kənˈsɜːn]": "беспокойство, озабоченоость",
    "capable [ˈkeɪpəbl]": "способный",
    "approach [əˈprəʊʧ]": "подход",
    "conclusion [kənˈkluːʒən]": "заключение, вывод",
    "thread [θred]": "нить",
    "moron [ˈmɔːrɒn]": "идиот",
    "nerd [nɜːd]": "тупица, кретин, умник",
    "collision [kəˈlɪʒən]": "столкновение, конфликт",
    "regardless [rɪˈgɑːdlɪs]": "несмотря на, независимо",
    "regard [rɪˈgɑːd]": "уважение",
    "spread [spred]": "распространение",
    "go back [gəʊ bæk]": "возвращаться",
    "surrender [səˈrendə]": "сдаваться",
    "mess [mes]": "беспорядок, путаница",
    "destruction [dɪsˈtrʌkʃn]": "разрушение",
    "make sense [meɪk sens]": "имеет смысл",
    "move on [muːv ɒn]": "двигаться дальше",
    "rather [ˈrɑːðə]": "скорее",
    "frightened [fraɪtnd]": "испуганный",
    "indeed [ɪnˈdiːd]": "действительно",
    "afterwards [ˈɑːftəwədz]": "впоследствии",
    "dice [daɪs]": "игральная кость",
    "rare [reə]": "с кровью, редкий",
    "lovely dinner": "прекрасный ужин",
    "glad [glæd]": "радостный",
    "bay [beɪ]": "залив",
    "Convention [kənˈvenʃn]": "соглашение",
    "recipient [rɪˈsɪpɪənt]": "получатель",
    "shave [ʃeɪv]": "бриться",
    "forecast [ˈfɔːkɑːst]": "прогноз",
    "as well as [æz wel æz]": "так же как",
    "Aquarius [əˈkwe(ə)rɪəs]": "водолей",
    "Pisces [ˈpaɪsiːz]": "рыбы",
    "Aries [ˈe(ə)riz]": "овен",
    "arrange [əˈreɪnʤ]": "организовывать",
    "Gemini [ˈʤemɪnaɪ]": "близнецы",
    "Taurus [ˈtɔːrəs]": "телец",
    "prompt [prɒmpt]": "побудить",
    "bother [ˈbɒðə]": "беспокоить",
    "briefcase [ˈbriːfkeɪs]": "портфель, чемоданчик",
    "suspicious [səsˈpɪʃəs]": "подозрительный",
    "addict [ˈædɪkt]": "пристрастие, наркоман",
    "romance [rəʊˈmæns]": "романтика",
    "violin [vaɪəˈlɪn]": "скрипка",
    "whatever [wɒtˈevə]": "что угодно",
    "wherever [we(ə)ˈrevə]": "где бы",
    "comparative [kəmˈpærətɪv]": "сравнительный, относительный",
    "superlative [sjuːˈpɜːlətɪv]": "превосходная степень",
    "participle [ˈpɑːtɪsɪpl]": "причастие",
    "chain [ʧeɪn]": "сеть, цепь",
    "related [rɪˈleɪtɪd]": "связанный",
    "rags [rægz]": "лохмотья, тряпье",
    "beggar [ˈbegə]": "нищий, попрошайка",
    "torn [tɔːn]": "порванный",
    "try on [traɪ ɒn]": "примерить",
    "put-on [ˈpʊtɒn]": "надевать",
    "take off [teɪk ɒf]": "снять",
    "suit [sjuːt]": "подходить",
    "skirt [skɜːt]": "юбка",
    "coat [kəʊt]": "пальто",
    "tracksuit [ˈtræks(j)uːt]": "спортивный костюм",
    "tights [taɪts]": "колготки",
    "trainers [ˈtreɪnəz]": "кроссовки",
    "ruin [ˈruːɪn]": "портить",
    "sail [seɪl]": "парус, плавать, отплыть",
    "whisper [ˈwɪspə]": "шопот",
    "burst [bɜːst]": "всплеск, вспышка",
    "evict [ɪˈvɪkt]": "выселять",
    "drives them mad": "сводит их сума",
    "washing up [ˈwɒʃɪŋ ʌp]": "мытье посуды",
    "yacht [jɒt]": "яхта",
    "treat [triːt]": "лечить, рассматривать",
    "contributing [kənˈtrɪbjuːtɪŋ]": "способствующий",
    "throw out [θrəʊ aʊt]": "выгонять, выбросить",
    "reduce [rɪˈdjuːs]": "уменьшить",
    "comparative [kəmˈpærətɪv]": "сравнительный",
    "acceleration [əkseləˈreɪʃn]": "ускорение",
    "less [les]": "меньше",
    "obsess [əbˈses]": "преследовать",
    "obsessed [əbˈsɛst]": "одержимость",
    "suffering [ˈsʌfərɪŋ]": "страдающий",
    "sickness [ˈsɪknɪs]": "болезнь",
    "newsreader [ˈnjuːzriːdə]": "дикторы новостей",
    "nowadays [ˈnaʊədeɪz]": "в наше время",
    "microwave [ˈmaɪkrəweɪv]": "микроволновая печь",
    "chic [ʃik]": "шикарный",
    "greengrocer [ˈgriːngrəʊsə]": "овощник",
    "gardener [ˈgɑːdnə]": "садовник",
    "inhabitant [ɪnˈhæbɪtənt]": "житель",
    "tube [tjuːb]": "трубка",
    "amount [əˈmaʊnt]": "сумма",
    "carefully [ˈkeəf(ə)lɪ]": "внимательно",
    "fall over [fɔːl ˈəʊvə]": "падать",
    "tape [teɪp]": "лента",
    "ahead [əˈhed]": "впереди, заранее",
    "straight ahead [streɪt əˈhed]": "прямо по курсу",
    "bit [bɪt]": "немного",
    "speculate [ˈspekjʊleɪt]": "размышлять, предположения",
    "kind of you": "мило с твоей стороны",
    "intention [ɪnˈtenʃn]": "намерение",
    "coast [kəʊst]": "побережье",
    "narrow [ˈnærəʊ]": "узкий",
    "attraction [əˈtrækʃn]": "привлекательность",
    "rubbish [ˈrʌbɪʃ]": "мусор, хлам",
    "engaged [ɪnˈgeɪʤd]": "обрученный",
    "lace [leɪs]": "кружево",
    "fiance [fɪˈɑːnseɪ]": "жених",
    "survival [səˈvaɪvəl]": "выживание",
    "pan [pæn]": "кастрюля, сковорода",
    "rapid [ˈræpɪd]": "быстро",
    "stain [steɪn]": "пятно",
    "covered [ˈkʌvəd]": "покрытый, защищенный",
    "moody [ˈmuːdɪ]": "угрюмый",
    "sickness [ˈsɪknɪs]": "болезнь",
    "interrupt [ɪntəˈrʌpt]": "прерывать",
    "convince [kənˈvɪns]": "убеждать",
    "headlines [ˈhedlaɪnz]": "громкие заголовки",
    "slow down [sləʊ daʊn]": "замедлиться",
    "plenty [ˈplentɪ]": "множество, масса",
    "approximately [əˈprɒksɪmɪtlɪ]": "примерно, приблизительно",
    "fare [feə]": "плата за проезд",
    "brief [briːf]": "краткий",
    "gathering [ˈgæðərɪŋ]": "сбор",
    "reception [rɪˈsepʃn]": "прием",
    "familiar [fəˈmɪlɪə]": "знакомый",
    "fascinating [ˈfæsɪneɪtɪŋ]": "очаровательный",
    "reinforce [riːɪnˈfɔːs]": "усиливать, укреплять",
    "mention [menʃn]": "упоминать",
    "consonant [ˈkɒnsənənt]": "созвучный",
    "breathe [briːð]": "дышать",
    "unaware [ʌnəˈweə]": "не подозревающий, не знающий",
    "don't mind": "не против",
    "dream of [driːm ɒv]": "мечтать днем",
    "dream about [driːm əˈbaʊt]": "мечтать во сне, сон",
    "can't stand": "ненавидеть",
    "choir [ˈkwaɪə]": "хор",
    "survey [ˈsɜːveɪ]": "опрос, анкетирование",
    "exclude [ɪksˈkluːd]": "исключить",
    "spark [spɑːk]": "искра",
    "express [ɪksˈpres]": "выражать",
    "imperative [ɪmˈperətɪv]": "обязательный, повелительный",
    "obligation [ɒblɪˈgeɪʃn]": "обязательство",
    "obligatory [əbˈlɪgət(ə)rɪ]": "обязательный",
    "permit [ˈpɜːmɪt]": "разрешать",
    "prohibit [prəˈhɪbɪt]": "запрещать",
    "tend [tend]": "тяготеть, клониться",
    "external [ɪkˈstɜːn(ə)l]": "внешний",
    "simplicity [sɪmˈplɪsɪtɪ]": "простота",
    "find out [faɪnd aʊt]": "выяснить",
    "chemist [ˈkemɪst]": "аптека",
    "pointing [ˈpɔɪntɪŋ]": "указание, указывающий",
    "hopefully [ˈhəʊpfəlɪ]": "с надеждой",
    "incredibly [ɪnˈkredəblɪ]": "невероятно, чрезвычайно",
    "quite [kwaɪt]": "довольно, вполне",
    "required [rɪˈkwaɪəd]": "требуемый",
    "towards [təˈwɔːdz]": "в направлении",
    "martial [ˈmɑːʃəl]": "боевые",
    "throw the ball [θrəʊ ðiː bɔːl]": "бросить мяч",
    "out of [aʊt ɒv]": "снаружи, из",
    "past [pɑːst]": "мимо",
    "insist [ɪnˈsɪst]": "настаивать",
    "movement [ˈmuːvmənt]": "передвижение",
    "keen [kiːn]": "проницательный, чуткий, пытливый",
    "pitch [pɪʧ]": "подача",
    "despair [dɪsˈpeə]": "отчаяние",
    "ecstatic [ɪkˈstætɪk]": "восторженный",
    "whistle [wɪsl]": "свисток",
    "injury [ˈɪnʤərɪ]": "травма",
    "due [djuː]": "надлежащий, сбор, пошлина",
    "commit [kəˈmɪt]": "совершить",
    "crime [kraɪm]": "преступление, злодеяние",
    "share [ʃeə]": "делиться",
    "bow [bəʊ]": "лук, поклон",
    "curtain [kɜːtn]": "занавес",
    "fame [feɪm]": "слава",
    "chorus [ˈkɔːrəs]": "хор",
    "gist [ʤɪst]": "суть",
    "irritate [ˈɪrɪteɪt]": "раздражать",
    "accommodation [əkɒməˈdeɪʃn]": "размещение, жилье",
    "yours faithfully [jɔːz ˈfeɪθf(ə)lɪ]": "искренне Ваш",
    "sincerely [sɪnˈsɪəlɪ]": "искренне",
    "honour [ˈɒnə]": "честь",
    "obviously [ˈɒbvɪəslɪ]": "очевидно",
    "access [ˈækses]": "доступ",
    "refund [ˈriːfʌnd]": "возврат денег",
    "never mind [ˈnevə maɪnd]": "неважно",
    "entertaining [entəˈteɪnɪŋ]": "развлекательный",
    "reliable [rɪˈlaɪəbl]": "надежный",
    "adapt [əˈdæpt]": "приспособиться",
    "demand [dɪˈmɑːnd]": "требование",
    "wedding reception [ˈwedɪŋ rɪˈsepʃn]": "свадебный банкет",
    "mystery [ˈmɪstərɪ]": "тайна",
    "guide [gaɪd]": "руководство",
    "occasional [əˈkeɪʒ(ə)nəl]": "случайный",
    "overlook [əʊvəˈlʊk]": "упускать из виду",
    "assimilate [əˈsɪmɪleɪt]": "усваивать",
    "memorize [ˈmeməraɪz]": "выучить наизусть",
    "confuse [kənˈfjuːz]": "запутывать, смущать",
    "explanation [ekspləˈneɪʃn] ": "объяснение, разъяснение",
    "consequence [ˈkɒnsɪkwəns]": "последствие",
    "investigate [ɪnˈvestɪgeɪt]": "исследовать",
    "spill [spɪl]": "проливать",
    "completion [kəmˈpliːʃn]": "завершение",
    "improbable [ɪmˈprɒbəbl]": "невероятный, неправдоподобный",
    "wasp [wɒsp]": "оса",
    "giraffe [ʤɪˈrɑːf]": "жираф",
    "dolphin [ˈdɒlfɪn]": "дельфин",
    "kangaroo [kæŋgəˈruː]": "кенгуру",
    "whale [weɪl]": "кит",
    "victim [ˈvɪktɪm]": "жертва",
    "weigh [weɪ]": "весить",
    "decisive [dɪˈsaɪsɪv]": "решительный",
    "indecisive [ɪndɪˈsaɪsɪv]": "нерешительный",
    "indecisive [ɪndɪˈsaɪsɪv]": "нерешительный",
    "make up my mind": "to decide",
    "skim [skɪm]": "бегло просматривать",
    "invitation [ɪnvɪˈteɪʃn]": "приглашение",
    "silly [ˈsɪlɪ]": "глупый",
    "extract [ˈekstrækt]": "извлекать, выдержка",
    "jealousy [ˈʤeləsɪ]": "ревность, зависть",
    "obsessive [əbˈsesɪv]": "навязчивый",
    "offend [əˈfend]": "обижать",
    "ought [ɔːt]": "следует",
    "cupboard [ˈkʌpbəd]": "шкаф, буфет, сервант",
    "desperate [ˈdespərɪt]": "отчаянный",
    "redistribute [riːdɪˈstrɪbjuːt]": "перераспределить",
    "volume [ˈvɒljuːm]": "величина",
    "sleeve [sliːv]": "рукав",
    "behaviour [bɪˈheɪvɪə]": "поведение",
    "painkiller [ˈpeɪnkɪlə]": "обезболивающее",
    "headache [ˈhedeɪk]": "головная боль",
    "backache [ˈbækeɪk]": "боли в спине",
    "cough [kɒf]": "кашель",
    "stomachache [ˈstʌməkeɪk]": "боль в животе",
    "toothache [ˈtuːθeɪk]": "зубная боль",
    "earache [ˈɪəreɪk]": "ушная боль",
    "hurt [hɜːt]": "ранить, болеть",
    "bless you [bles juː]": "будьте здоровы",
    "sneeze [sniːz]": "чихать",
    "affair [əˈfeə]": "дело, событие",
    "bald [bɔːld]": "лысый",
    "put on weight [pʊt ɒn weɪt]": "набрать вес",
    "violent [ˈvaɪələnt]": "насильственный",
    "ladder [ˈlædə]": "лестница, трап, стремянка",
    "well [wel]": "колодец",
    "dig [dɪg]": "копать",
    "tournament [ˈtʊənəmənt]": "турнир",
    "hike [haɪk]": "гулять",
    "hiking [ˈhaɪkɪŋ]": "пеший туризм",
    "wilderness [ˈwɪldənɪs]": "Дикая местность",
    "bark [bɑːk]": "кора",
    "drown [draʊn]": "тонуть",
    "conclude [kənˈkluːd]": "заключать, заключить",
    "inject [ɪnˈʤekt]": "впрыскивать, инъецировать, впрыснуть",
    "flu [fluː]": "грипп",
    "character [ˈkærɪktə]": "характер, образ, герой",
    "tricky [ˈtrɪkɪ]": "хитрый, коварный",
    "cattle [kætl]": "крупный рогатый скот",
    "honorary [ˈɒnərərɪ]": "почётный",
    "rebel [rebl]": "бунтарь",
    "behave [bɪˈheɪv]": "вести себя",
    "performance [pəˈfɔːməns]": "представление, спектакль",
    "performing [pəˈfɔːmɪŋ]": "выступающий",
    "perform [pəˈfɔːm]": "выполнять",
    "appalling [əˈpɔːlɪŋ]": "ужасающий",
    "contribution [kɒntrɪˈbjuːʃn]": "вклад",
    "deteriorated [dɪˈtɪərɪəreɪtɪd]": "ухудшенный",
    "rope [rəʊp]": "веревка, трос, канат",
    "humiliate [hjuːˈmɪlɪeɪt]": "унижать",
    "affirmative [əˈfɜːmətɪv]": "утвердительный",
    "feasible [ˈfiːzəbl]": "осуществимый",
    "aching [ˈeɪkɪŋ]": "болящий, ноющий",
    "ease [iːz]": "легкость, простота, непринужденность",
    "assume [əˈsjuːm]": "предполагать",
    "assumption [əˈsʌmpʃn]": "предположение",
    "significant [sɪgˈnɪfɪkənt]": "существенный, значительный",
    "discover [dɪsˈkʌvə]": "обнаруживать, находить, раскрывать",
    "pun [pʌn]": "каламбур, игра слов",
    "necessity [nɪˈsesɪtɪ]": "необходимость, нужда",
    "dishwasher [ˈdɪʃwɒʃə]": "посудомойка",
    "disposable [dɪsˈpəʊzəbl]": "одноразовый",
    "nappy [ˈnæpɪ] diaper [ˈdaɪəpə]": "подгузник",
    "stockings [ˈstɒkɪŋz]": "чулки, колготки",
    "windscreen [ˈwɪndskriːn]": "ветровое стекло, лобовое стекло",
    "wiper [ˈwaɪpə]": "дворник, стеклоочиститель",
    "biro [ˈbaɪ(ə)rəʊ]": "шариковая ручка",
    "vacuum cleaner [ˈvækjʊəm ˈkliːnə]": "пылесос",
    "vest [vest]": "жилет, бронежилет",
    "frustrate [frʌ'streɪt]": "расстраивать, разочаровывать",
    "explode [ɪksˈpləʊd]": "взрывать, взрываться",
    "light-bulb [laɪt-bʌlb]": "лампочка",
    "cure [kjʊə]": "лечение, лекарство",
    "distinguish [dɪsˈtɪŋgwɪʃ]": "различать, отличать, проводить различие",
    "cab [kæb]": "такси",
    "statue [ˈstæjuː]": "статуя",
    "wonder [ˈwʌndə]": "удивляться",
    "chapel [ˈʧæpəl]": "часовня, капелла, молельня",
    "centenarian [sentɪˈne(ə)rɪən]": "долгожитель",
    "gear [gɪə]": "механизм",
    "spite [spaɪt]": "злоба, несмотря на",
    "rebellious [rɪˈbeljəs]": "мятежный, бунтарный",
    "assassinate [əˈsæsɪneɪt]": "убивать, убить",
    "copper [ˈkɒpə]": "медь",
    "tin [tɪn]": "олово",
    "aisle [aɪl]": "проход, пролет",
    "nickel [nɪkl]": "никель, цент",
    "dime [daɪm]": "десятицентовик",
    "quarters [ˈkwɔːtəz]": "помещение",
    "disability [dɪsəˈbɪlɪtɪ]": "инвалидностьsss",
    "compound [ˈkɒmpaʊnd]": "соединение",
    "trap [træp]": "ловушка",
    "suppose [səˈpəʊz]": "предполагать",
    "exhausted [ɪgˈzɔːstɪd]": "измученный, истощенный, обессиленный",
    "convey [kənˈveɪ]": "выражать, сообщить, донести",
    "irritable [ˈɪrɪtəbl]": "раздражительный",
    "gentle [ʤentl]": "нежный, легкий, короткий",
    "particle [ˈpɑːtɪkl]": "частица, крупица",
    "look up [lʊk ʌp]": "поиск",
    "stay up [steɪ ʌp]": "не ложиться спать",
    "be over [biː ˈəʊvə]": "закончиться",
    "put away [pʊt əˈweɪ]": "убрать, убирать",
    "throw away [θrəʊ əˈweɪ]": "выбрасывать",
    "turn down [tɜːn daʊn]": "убавить, уменьшить",
    "fill in [fɪl ɪn]": "заполнять",
    "find out [faɪnd aʊt]": "узнать, разузнать",
    "hurry up [ˈhʌrɪ ʌp]": "торопиться",
    "purse [pɜːs]": "кошелек",
    "adopted [əˈdɒptɪd]": "усыновленный",
    "enormous [ɪˈnɔːməs]": "огромный",
    "put through [pʊt θruː]": "соединять",
    "is that Lisa": "NOT Are you Lisa",
    "It's Anuar": "NOT I am Anuar",
    "hold on": "wait",
    "above all [əˈbʌv ɔːl]": "превыше всего, прежде всего, в первую очередь",
    "NAP [næp]": "дремать, дрема",
    "bring up [brɪŋ ʌp] brought up [brɔːt ʌp]": "воспитывать, выращенный",
    "eve [iːv]": "канун",
    "day-off": "выходной",
    "on my own [ɒn maɪ əʊn]": "самостоятельно",
    "tan [tæn]": "загар",
    "attitude [ˈætɪtjuːd]": "отношение, подход",
    "tense [tens]": "натянутый, напряженный",
    "go wrong [gəʊ rɒŋ]": "сорваться, выйти из строя",
    "belief [bɪˈliːf]": "вера, убеждение",
    "sunset [ˈsʌnset]": "закат",
    "freeway [ˈfriːweɪ] motorway [ˈməʊtəweɪ]": "автострада",
    "fiction [fɪkʃn]": "вымысел",
    "raffle [ræfl]": "лотерея, розыгрыш",
    "fine [faɪn]": "штраф, пеня",
    "snoring [ˈsnɔːrɪŋ]": "храп",
    "affair [əˈfeə]": "дело, событие",
    "rob [rɒb]": "грабить",
    "accidentally [æksɪˈdentəlɪ]": "случайно",
    "mingle [mɪŋgl]": "смешивать",
}


import json

with open('learning.json', 'w') as f:
    json.dump(dict, f)
